[workspace]
resolver = "2"
members = ["crates/usg-core", "crates/usg-cli", "crates/usg-ffi"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.80"

[workspace.dependencies]
usg-core = { path = "crates/usg-core" }
walkdir = "2"
ignore = "0.4"
rayon = "1.10"
libc = "0.2"
serde_json = "1"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
panic = "abort"
opt-level = 3
