import Darwin

public struct LockfileIO {

    /// Scan + write the lockfile for `projectRoot` (creates the generator dir if needed).
    public static func scanAndWrite(projectRoot: String) throws -> Lockfile {
        let path = lockfilePath(for: projectRoot)
        createDirectoryRecursive(parentDirectory(of: path))
        let lockfile = try LockfileScanner.scan(projectRoot: projectRoot)
        try write(lockfile, to: path)
        return lockfile
    }

    /// Read the lockfile if present, else scan + write a fresh one.
    public static func loadOrScan(projectRoot: String) throws -> Lockfile {
        let path = lockfilePath(for: projectRoot)
        if fileExists(path) { return try read(from: path) }
        return try scanAndWrite(projectRoot: projectRoot)
    }

    package static func write(_ lockfile: Lockfile, to path: String) throws {
        var s = ""
        s += "# csproj.lock — auto-generated by unity-solution-generator lock\n"
        s += "# Re-run when: Unity version changes, packages added/removed\n\n"
        s += "unity-version: \(lockfile.unityVersion)\n"
        s += "unity-path: \(lockfile.unityPath)\n"
        s += "lang-version: \(lockfile.langVersion)\n"

        writeSection(&s, "analyzers", lines: lockfile.analyzers)
        for cat in RefCategory.allCases {
            writeRefSection(&s, cat.rawValue, refs: lockfile.refs[cat] ?? [])
        }

        s += "\n[defines]\n"
        s += lockfile.defines.joined(separator: ";") + "\n"

        s += "\n[defines.scripting]\n"
        s += lockfile.definesScripting.joined(separator: ";") + "\n"

        try writeFileIfChanged(path, s)
    }

    public static func read(from path: String) throws -> Lockfile {
        let content = try readFile(path)

        var unityVersion = ""
        var unityPath = ""
        var langVersion = "9.0"
        var analyzers: [String] = []
        var refs: [RefCategory: [DllRef]] = [:]
        var defines: [String] = []
        var definesScripting: [String] = []

        enum Section {
            case analyzers
            case ref(RefCategory)
            case defines
            case definesScripting
        }
        var currentSection: Section? = nil

        for rawLine in content.split(separator: "\n", omittingEmptySubsequences: false) {
            let line = String(rawLine)
            if line.isEmpty || line.hasPrefix("#") { continue }

            // Section header
            if line.hasPrefix("[") && line.hasSuffix("]") {
                let name = String(line.dropFirst().dropLast())
                if let cat = RefCategory(rawValue: name) {
                    currentSection = .ref(cat)
                } else {
                    switch name {
                    case "analyzers": currentSection = .analyzers
                    case "defines": currentSection = .defines
                    case "defines.scripting": currentSection = .definesScripting
                    default: currentSection = nil
                    }
                }
                continue
            }

            // Header key-value (before any section)
            if currentSection == nil {
                if let (key, value) = parseHeaderLine(line) {
                    switch key {
                    case "unity-version": unityVersion = value
                    case "unity-path": unityPath = value
                    case "lang-version": langVersion = value
                    default: break
                    }
                }
                continue
            }

            // Section content
            switch currentSection {
            case .analyzers:
                analyzers.append(line)
            case .ref(let cat):
                if let ref = parseDllRef(line) { refs[cat, default: []].append(ref) }
            case .defines:
                if !line.isEmpty {
                    defines = line.split(separator: ";").map(String.init)
                }
            case .definesScripting:
                if !line.isEmpty {
                    definesScripting = line.split(separator: ";").map(String.init)
                }
            case nil:
                break
            }
        }

        guard !unityVersion.isEmpty else {
            throw LockfileError.invalidLockfile("missing unity-version")
        }
        guard !unityPath.isEmpty else {
            throw LockfileError.invalidLockfile("missing unity-path")
        }

        return Lockfile(
            unityVersion: unityVersion,
            unityPath: unityPath,
            langVersion: langVersion,
            analyzers: analyzers,
            refs: refs,
            defines: defines,
            definesScripting: definesScripting
        )
    }
}

// MARK: - Writing helpers

private func writeSection(_ s: inout String, _ name: String, lines: [String]) {
    s += "\n[\(name)]\n"
    for line in lines { s += "\(line)\n" }
}

private func writeRefSection(_ s: inout String, _ name: String, refs: [DllRef]) {
    s += "\n[\(name)]\n"
    for ref in refs { s += "\(ref.name)|\(ref.path)\n" }
}

// MARK: - Parsing helpers

private func parseHeaderLine(_ line: String) -> (key: String, value: String)? {
    guard let colonIdx = line.firstIndex(of: ":") else { return nil }
    let key = String(line[..<colonIdx])
    let valueStart = line.index(after: colonIdx)
    let value = trimWhitespace(String(line[valueStart...]))
    return (key, value)
}

private func parseDllRef(_ line: String) -> DllRef? {
    guard let pipeIdx = line.firstIndex(of: "|") else { return nil }
    let name = String(line[..<pipeIdx])
    let path = String(line[line.index(after: pipeIdx)...])
    return DllRef(name: name, path: path)
}
