import Darwin

struct LockfileIO {

    static func write(_ lockfile: Lockfile, to path: String) throws {
        var s = ""
        s += "# csproj.lock — auto-generated by unity-solution-generator lock\n"
        s += "# Re-run when: Unity version changes, packages added/removed\n\n"
        s += "unity-version: \(lockfile.unityVersion)\n"
        s += "unity-path: \(lockfile.unityPath)\n"
        s += "lang-version: \(lockfile.langVersion)\n"

        writeSection(&s, .analyzers, lines: lockfile.analyzers)
        writeRefSection(&s, .refsEngine, refs: lockfile.refsEngine)
        writeRefSection(&s, .refsEditor, refs: lockfile.refsEditor)
        writeRefSection(&s, .refsNetstandard, refs: lockfile.refsNetstandard)
        writeRefSection(&s, .refsPlaybackIos, refs: lockfile.refsPlaybackIos)
        writeRefSection(&s, .refsPlaybackAndroid, refs: lockfile.refsPlaybackAndroid)
        writeRefSection(&s, .refsPlaybackStandalone, refs: lockfile.refsPlaybackStandalone)
        writeRefSection(&s, .refsProject, refs: lockfile.refsProject)

        s += "\n[\(Section.defines.rawValue)]\n"
        s += lockfile.defines.joined(separator: ";") + "\n"

        s += "\n[\(Section.definesScripting.rawValue)]\n"
        s += lockfile.definesScripting.joined(separator: ";") + "\n"

        try writeFileIfChanged(path, s)
    }

    static func read(from path: String) throws -> Lockfile {
        let content = try readFile(path)

        var unityVersion = ""
        var unityPath = ""
        var langVersion = "9.0"
        var analyzers: [String] = []
        var refsEngine: [DllRef] = []
        var refsEditor: [DllRef] = []
        var refsNetstandard: [DllRef] = []
        var refsPlaybackIos: [DllRef] = []
        var refsPlaybackAndroid: [DllRef] = []
        var refsPlaybackStandalone: [DllRef] = []
        var refsProject: [DllRef] = []
        var defines: [String] = []
        var definesScripting: [String] = []

        var currentSection: Section? = nil

        for rawLine in content.split(separator: "\n", omittingEmptySubsequences: false) {
            let line = String(rawLine)
            if line.isEmpty || line.hasPrefix("#") { continue }

            // Section header
            if line.hasPrefix("[") && line.hasSuffix("]") {
                let name = String(line.dropFirst().dropLast())
                currentSection = Section(rawValue: name)
                continue
            }

            // Header key-value (before any section)
            if currentSection == nil {
                if let (key, value) = parseHeaderLine(line) {
                    switch key {
                    case "unity-version": unityVersion = value
                    case "unity-path": unityPath = value
                    case "lang-version": langVersion = value
                    default: break
                    }
                }
                continue
            }

            // Section content
            switch currentSection {
            case .analyzers:
                analyzers.append(line)
            case .refsEngine:
                if let ref = parseDllRef(line) { refsEngine.append(ref) }
            case .refsEditor:
                if let ref = parseDllRef(line) { refsEditor.append(ref) }
            case .refsNetstandard:
                if let ref = parseDllRef(line) { refsNetstandard.append(ref) }
            case .refsPlaybackIos:
                if let ref = parseDllRef(line) { refsPlaybackIos.append(ref) }
            case .refsPlaybackAndroid:
                if let ref = parseDllRef(line) { refsPlaybackAndroid.append(ref) }
            case .refsPlaybackStandalone:
                if let ref = parseDllRef(line) { refsPlaybackStandalone.append(ref) }
            case .refsProject:
                if let ref = parseDllRef(line) { refsProject.append(ref) }
            case .defines:
                if !line.isEmpty {
                    defines = line.split(separator: ";").map(String.init)
                }
            case .definesScripting:
                if !line.isEmpty {
                    definesScripting = line.split(separator: ";").map(String.init)
                }
            case nil:
                break
            }
        }

        guard !unityVersion.isEmpty else {
            throw LockfileError.invalidLockfile("missing unity-version")
        }
        guard !unityPath.isEmpty else {
            throw LockfileError.invalidLockfile("missing unity-path")
        }

        return Lockfile(
            unityVersion: unityVersion,
            unityPath: unityPath,
            langVersion: langVersion,
            analyzers: analyzers,
            refsEngine: refsEngine,
            refsEditor: refsEditor,
            refsNetstandard: refsNetstandard,
            refsPlaybackIos: refsPlaybackIos,
            refsPlaybackAndroid: refsPlaybackAndroid,
            refsPlaybackStandalone: refsPlaybackStandalone,
            refsProject: refsProject,
            defines: defines,
            definesScripting: definesScripting
        )
    }
}

// MARK: - Sections

private enum Section: String {
    case analyzers
    case refsEngine = "refs.engine"
    case refsEditor = "refs.editor"
    case refsNetstandard = "refs.netstandard"
    case refsPlaybackIos = "refs.playback.ios"
    case refsPlaybackAndroid = "refs.playback.android"
    case refsPlaybackStandalone = "refs.playback.standalone"
    case refsProject = "refs.project"
    case defines
    case definesScripting = "defines.scripting"
}

// MARK: - Writing helpers

private func writeSection(_ s: inout String, _ section: Section, lines: [String]) {
    s += "\n[\(section.rawValue)]\n"
    for line in lines { s += "\(line)\n" }
}

private func writeRefSection(_ s: inout String, _ section: Section, refs: [DllRef]) {
    s += "\n[\(section.rawValue)]\n"
    for ref in refs { s += "\(ref.name)|\(ref.path)\n" }
}

// MARK: - Parsing helpers

private func parseHeaderLine(_ line: String) -> (key: String, value: String)? {
    guard let colonIdx = line.firstIndex(of: ":") else { return nil }
    let key = String(line[..<colonIdx])
    let valueStart = line.index(after: colonIdx)
    let value = trimWhitespace(String(line[valueStart...]))
    return (key, value)
}

private func parseDllRef(_ line: String) -> DllRef? {
    guard let pipeIdx = line.firstIndex(of: "|") else { return nil }
    let name = String(line[..<pipeIdx])
    let path = String(line[line.index(after: pipeIdx)...])
    return DllRef(name: name, path: path)
}
